@startuml
scale 500 width

[*] --> НоваяДоска

state НоваяДоска {
  [*] --> ВыборСкрытости : Создать новую доску
  ВыборСкрытости --> ДобавлениеУчастников : Скрытость выбрана
  ДобавлениеУчастников --> СозданиеКолонок : Участники добавлены
  ДобавлениеУчастников --> ВыборСкрытости : Отмена
  ВыборСкрытости --> НоваяДоска : Отмена
}

state СозданиеКолонок {
  [*] --> Активный
  Активный --> СозданиеКарточек : Добавить колонку
}

state СозданиеКарточек {
  [*] --> Активный
  Активный --> СозданиеКолонок : Добавить карточку
}

@enduml
