@startuml
(*) --> "Нажатие кнопки 'Войти'"
--> "Ввод данных"
if "Пользователь ввел данные" then
  --> [Данные введены] "Система проверяет корректность данных"
  if "Данные корректны" then
    --> [Данные корректны] "Система отображает главное окно"
    --> "Завершение авторизации"
  else
    --> [Данные не корректны] "Система отображает сообщение об ошибке"
  endif
else
  --> [Данные не введены] "Система отображает сообщение об ошибке"
endif
@enduml
